### ISSUE TITLE
Week 1 Task List

### ISSUE THREAD

**Issue by stellashen0911** [SplitAppTeam/Split-App-Development#1]
Initialize the project from scratch.
- [x] User sees app icon in home screen and styled launch screen.
- [x] Set up the sign up and sign in storyboard.
- [ ] User can sign up to create a new account.
- [ ] User can log in.
- [x] Set up the backend server.
- [x] design app icons 
- [x] Add Parse client to an Xcode project

**Comment by snowyaya** [comment]
Completed week1 task

- [x] User sees app icon in home screen and styled launch screen.
- [x]  Set up the sign up and sign in storyboard.
- [x]  User can sign up to create a new account.
- [x]  User can log in.
- [x]  Set up the backend server.
- [x]  design app icons
- [x]  Add Parse client to an Xcode project
